import React from "react";
import { Modal, Image, Col, Container, Row } from "react-bootstrap";
import Heading from "./Heading";
import ScrollAnimation from "react-animate-on-scroll";
function TermsModal(props) {
  return (
    <>
      <Modal
        className="termsModal"
        size="xl"
        id="OBRModal"
        show={props.show}
        onHide={props.handleClose}
      >
        <Modal.Header className="p-0 border-0 pb-2 justify-content-end">
          <button
            type="button"
            className="border-0 bg-transparent p-3"
            onClick={props.handleClose}
          >
            <Image src="/assets/i/cross.svg" className="cross" />
          </button>
        </Modal.Header>
        <Modal.Body className="p-0">
          <div className="story-section mission-section" id="roadmap">
            <Container fluid>
              <ScrollAnimation className="animate__animated animate__animate__slideInLeft">
                <Heading Title="Terms & Conditions " />
                <Row className="align-items-center">
                  <Col lg="12">
                    <div className="story-text">
                      <p>
                        The First Arabs is a collection of digital artworks
                        (NFTs) running on the Ethereum network. This website is
                        only an interface allowing participants to exchange
                        digital collectibles. Users are entirely responsible for
                        the safety and management of their own private Ethereum
                        wallets and validating all transactions and contracts
                        generated by this website before approval. Furthermore,
                        as The First Arabs smart contract runs on the Ethereum
                        network, there is no ability to undo, reverse, or
                        restore any transactions.
                      </p>
                      <p>
                        This website and its connected services are provided “as
                        is” and “as available” without warranty of any kind. By
                        using this website you are accepting sole responsibility
                        for any and all transactions involving The First Arabs
                        digital collectibles.
                      </p>
                    </div>
                  </Col>
                </Row>
              </ScrollAnimation>
            </Container>
          </div>
          <div className="story-section mission-section" id="roadmap">
            <Container fluid>
              <ScrollAnimation className="animate__animated animate__animate__slideInLeft">
                <Heading Title="Ownership " />
                <Row className="align-items-center">
                  <Col lg="12">
                    <div className="story-text">
                      <p>
                        i. You Own the NFT. Each First Arab is an NFT on the
                        Ethereum blockchain. When you purchase an NFT, you own
                        the underlying First Arab, the Art, completely.
                        Ownership of the NFT is mediated entirely by the Smart
                        Contract and the Ethereum Network: at no point may we
                        seize, freeze, or otherwise modify the ownership of any
                        First Arab.
                      </p>
                      <p>
                        ii. Personal Use. Subject to your continued compliance
                        with these Terms, Desert Labs grants you a worldwide,
                        royalty-free license to use, copy, and display the
                        purchased Art, along with any extensions that you choose
                        to create or use, solely forthe following purposes: (i)
                        for your own personal, non-commercial use; (ii) as part
                        of a marketplace that permits the purchase and sale of
                        your First Arabs / NFT, provided that the marketplace
                        cryptographically verifies each First Arabs owner’s
                        rights to display the Art for their First Arab to ensure
                        that only the actual owner can display the Art; or (iii)
                        as part of a third party website or application that
                        permits the inclusion, involvement, or participation of
                        your First Arab, provided that the website/application
                        cryptographically verifies each First Arab owner’s
                        rights to display the Art for their First Arab to ensure
                        that only the actual owner can display the Art, and
                        provided that the Art is no longer visible once the
                        owner of the First Arab leaves the website/application.
                      </p>
                      <p>
                        iii. Commercial Use. Subject to your continued
                        compliance with these Terms, Desert Labs grants you an
                        unlimited, worldwide license to use, copy, and display
                        the purchased Art for the purpose of creating derivative
                        works based upon the Art (“Commercial Use”). Examples of
                        such Commercial Use would e.g. be the use of the Art to
                        produce and sell merchandise products (T-Shirts etc.)
                        displaying copies of the Art. For the sake of clarity,
                        nothing in this Section will be deemed to restrict you
                        from (i) owning or operating a marketplace that permits
                        the use and sale of The First Arabs generally, provided
                        that the marketplace cryptographically verifies each
                        First Arab owner’s rights to display the Art for their
                        First Arab to ensure that only the actual owner can
                        display the Art; (ii) owning or operating a third party
                        website or application that permits the inclusion,
                        involvement, or participation of The First Arabs
                        generally, provided that the third party website or
                        application cryptographically verifies each First Arab
                        owner’s rights to display the Art for their First Arab
                        to ensure that only the actual owner can display the
                        Art, and provided that the Art is no longer visible once
                        the owner of the Purchased First Arab leaves the
                        website/application; or (iii) earning revenue from any
                        of the foregoing.
                      </p>
                    </div>
                  </Col>
                </Row>
              </ScrollAnimation>
            </Container>
          </div>
        </Modal.Body>
      </Modal>
    </>
  );
}

export default TermsModal;
